# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: name-tests-test
        # testing helper funcs / funcs that are used in multiple test-fiels
        exclude: ^tests/testing_helpers.py$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.285
  hooks:
    - id: ruff
# -   repo: https://github.com/shellcheck-py/shellcheck-py
#     rev: v0.9.0.5
#     hooks:
#     -   id: shellcheck
- repo: local
  hooks:
    # - id: simple-pylint
    #   name: simple-pylint
    #   entry: pylint
    #   args: ["api/"]
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    # - id: inline-pylint-with-bash
    #   name: inline-pylint-with-bash
    #   entry: bash -c 'lines=$(pylint api/ | wc -l) && (( lines > 10)) && exit 1'
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    - id: build-container-image
      name: build container image
      entry: bash ./build-container-image.sh
      language: system
      types: [dockerfile]
      files: ^Dockerfile$|^containerfile$
      verbose: true
      pass_filenames: false

default_language_version:
  python: python3.11

default_stages: [commit, push]
