FROM python:3.12-bookworm as builder

RUN pip install poetry==1.6.1

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN touch README.md

RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --only main --no-root

FROM python:3.12-slim-bookworm as runtime

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

WORKDIR /app

COPY moe_bot_auth_server/ /app/moe_bot_auth_server/

COPY config/ /app/config/

COPY templates/ /app/templates/

COPY static/ /app/static/

COPY entrypoint.sh gunicorn.conf.py create_server_db.py /app/

EXPOSE 8080

ENTRYPOINT ["/bin/sh","./entrypoint.sh"]
