version: "3.3"
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./envs/mariadb.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: mariadb
    restart: unless-stopped
  moe_bot_auth_server:
    image: localhost/moe_bot_auth_server:latest
    ports:
      - "8080:8080"
    container_name: moe_bot_auth_server
    hostname: moe_bot_auth_server
    # restart: unless-stopped
    env_file:
      ./envs/moe_bot_auth_server_prod.env
    depends_on:
      - db
volumes:
  db_data:
